---
title: "Setting up an R workflow"
---

## Working directory

In one of the previous steps, we:

-   Created a folder for the project of translating a microsimulation `EPL/devCEQaux`.
-   Cloned example microsimulation in Stata from [https://github.com/wbEPL/Example_FiscalSim](https://github.com/wbEPL/Example_FiscalSim){.uri style="font-size: 11pt;"} to the folder `EPL/devCEQaux/Example_FiscalSim/`.

Now, we need to create a project for our analysis in R, which will subsequently become a place, where we will develop out R Shiny application with the microsimulation.

### Creating an RStudio project

In your root folder, where you perform translation of the analysis to R and execute Stata code, (in this example, this is `EPL/devCEQaux` folder) create an R Studio project.

-   Familiarize with RStudio project basics here if needed [R4DS. Workflow: scripts and projects](https://r4ds.hadley.nz/workflow-scripts.html){style="font-size: 11pt;"}.
-   Use a short and concise name for the project. (It must not contain spaces and be short, up to 20 characters long).
    -   For example, use the same name as the Stata project has and add "\_app" to it The results is: "". In this way you will discriminate where is the original Stata project and where is the R version of it.
-   The result of creating the RStudio project `EPL/devCEQaux/Example_FiscalSim_app.` is following folder structure:
    -  Note. In the R Studio project folder, there is a file `Example_FiscalSim_app.Rproj`. Doubleclicking on this file will start R Studio for you.

The result is the following folder structure:

```{r eval=FALSE, include=FALSE, echo=FALSE}
fs::dir_tree("C:/Users/wb532966/OneDrive - WBG/EPL/devCEQaux")
```

```
./EPL/devCEQaux
├── Example_FiscalSim
│   ├── 01.Data
│   │   └── ...
│   ├── 02.Dofile
│   │   └── ...
│   ├── 03.Tool
│   │   └── Example_FiscalSim.xlsx
│   └── README.md
└── Example_FiscalSim_app
    └── Example_FiscalSim_app.Rproj
```

### Organizing files in the R Project.


### Creating first R script

Create 

 
